# Giới thiệu về NumPy

- NumPy là một Python Package, viết tắt của "Numerical Python", là một thư viện bao gồm các đối tượng mảng đa chiều và một tập hợp các quy trình để xử lý dữ liệu dạng mảng đó. Các phép toán và logic xử lý trên mảng dữ liệu có thể được thực hiện dễ dàng hơn với NumPy.

- Numeric, tổ tiên của NumPy, được phát triển bởi Jim Hugunin. Một gói khác Numarray cũng được phát triển, có một số chức năng bổ sung. Năm 2005, Travis Oliphant đã tạo ra gói NumPy bằng cách kết hợp các tính năng của Numarray vào gói Numeric. Có rất nhiều người đóng góp cho dự án mã nguồn mở này.

- https://numpy.org/doc/stable/user/whatisnumpy.html

# Cài đặt NumPy

In [1]:
# pip install numpy

# import numpy vào chương trình

In [2]:
# import numpy và gán nó bằng biến tên là np
import numpy as np

In [3]:
print (np.__version__)

1.12.1


# Làm việc với Python Numpy Array

- Mảng trong Numpy là một bảng các phần tử (thường là số), tất cả đều thuộc cùng một kiểu, được lập chỉ mục với số nguyên dương (bắt đầu từ chỉ số 0). Trong Numpy, số kích thước của mảng được gọi là thứ hạng của mảng. 
- Nhiều số nguyên cho kích thước của mảng dọc theo mỗi chiều được gọi là hình dạng của mảng. 
- Một lớp mảng trong Numpy được gọi là ndarray. 
- Các phần tử trong mảng Numpy được truy cập bằng cách sử dụng dấu ngoặc vuông và có thể được khởi tạo bằng cách sử dụng Python Lists lồng nhau.

# Các thao tác cơ bản với NumPy Array

In [4]:
list=[1,2,3,4,5]
npa=np.array(list)
npa

array([1, 2, 3, 4, 5])

In [5]:
# Kiểm tra kiểu dữ liệu của lis và npa
type(list),type(npa)

(list, numpy.ndarray)

In [6]:
# Chuyển lis từ dạng List sang NumPy Array và gán nó vào biến npa


# Hiển thị dữ liệu dạng mảng


In [7]:
# Bạn có thể ktra kích thước của mảng NumPy array bằng thuộc tính shape như sau
npa.shape
# Kết quả trả về là 5 dòng và 1 cột (Mặc định nhỏ nhất là 1 cột)

(5,)

In [8]:
# Giờ ta sẽ thử đưa thêm dữ liệu vào lis và chuyển nó qua dạng array của NumPy nhé


In [9]:
list.append(6)


In [10]:
npa=np.array(list)
npa

array([1, 2, 3, 4, 5, 6])

In [11]:
# Giờ ta thử thêm vào 1 giá trị chuỗi và thực hiện lại các công việc ở trên


In [12]:
list.append('IMIC Technology')

In [13]:
npa=np.array(list)
npa

array(['1', '2', '3', '4', '5', '6', 'IMIC Technology'], 
      dtype='<U21')

In [14]:
# Giờ chúng ta sẽ học cách làm sao để kết nối 2 list thành 1


In [15]:
# Kết nối 2 list làm 1 bằng toán tử cộng (+)
list2=[1,4,9,16]
list+=list2
list

[1, 2, 3, 4, 5, 6, 'IMIC Technology', 1, 4, 9, 16]

In [16]:
# Thêm 1 phần tử là 20 là lis kết hợp trên
list.append(20)

In [17]:
# Tiến hành chuyển sang dạng NumPy array như sau:
npa=np.array(list)
npa

array(['1', '2', '3', '4', '5', '6', 'IMIC Technology', '1', '4', '9',
       '16', '20'], 
      dtype='<U21')

# Làm việc với mảng nhiều chiều (List of list)

In [18]:
# lis4 là 1 list mà mỗi phần tử lại là 1 list khác
# Chúng ta còn gọi loại list này là List of List
list4=[[1,2],[3,4],[5,6]]

In [19]:
# Chuyển lis4 sang NumPy Array và gán vào biến npa2d
npa2d=np.array(list4)

In [20]:
# npa2d là 1 mảng 2 chiều (2D: 2 dimensions - 2 chiều)
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# Kiểm tra kích thước của npa2d
npa2d.shape
# Kết quả trả về là 3 dòng và 2 cột => mảng 2 chiều

(3, 2)

# Chuyển đổi kiểu dữ liệu khi tạo Array

- Ta sử dụng thêm từ khoá là dtype (dtype: data type <kiểu dữ liệu>)
- Và ở đây ta sẽ chuyển sang kiểu dữ liệu là float (Số thực)

In [22]:
npa2d = np.array(list4,dtype='float')
npa2d

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

- Giờ nếu chúng ta muốn chuyển dữ liệu trong NumPy Array từ float về integer
- Bạn sẽ sử dụng hàm astype(<kiểu dữ liệu>) để chuyển đổi kiểu dữ liệu của các phần tử trong NumPy array

In [23]:
npa2d.astype('str')

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['5.0', '6.0']], 
      dtype='<U32')

- Và cũng tương tự như trên, bạn cũng có thể chuyển đổi kiểu dữ liệu từ số nguyên (integer: int)
- sang chuỗi (string: str) như sau:

In [24]:
npa2d=npa2d.astype('int')
npa2d
npa2d.astype('str')


array([['1', '2'],
       ['3', '4'],
       ['5', '6']], 
      dtype='<U21')

- Giờ bạn muốn lấy ra các giá trị trong NumPy Array thì sẽ làm thế nào?
- Lấy ra phần tử thứ 1

In [25]:
npa2d[0]

array([1, 2])

- Tiếp tục thực hiện việc lấy ra giá trị thứ nhất của phần tử thứ nhất
- Vì phần tử thứ nhất là 1 list có 2 phần tử nên ta làm như sau:

In [26]:
npa2d[0][1]

2

- Giờ ta sẽ thử chuyển npa2d thành dữ liệu kiểu chuỗi:

In [27]:
npa2d = npa2d.astype('str')
npa2d[2][1]+'1'

'61'

- Hoặc bạn cũng có thể làm như sau:

In [28]:
npa2d[0][0]+'1'

'11'

# Hiểu rõ về np.nan và np.inf trong Python
- nan: Not a Number (Không phải số - Không xác định nên sẽ không bằng nhau)
- inf: Infinity (Dương vô cùng và Âm vô cùng: Nói chung là số vô cùng lớn)

- Hãy thử sử dụng hàm type để kiểm tra 1 giá trị "nan" và "inf"

In [29]:
print(f"nan: {type(np.nan)}")
print(f"inf: {type(np.inf)}")

nan: <class 'float'>
inf: <class 'float'>


- Hiển thị ra giá trị của "nan" và "inf":

In [30]:
print(f"Giá trị nan: {np.nan}")
print(f"Giá trị inf: {np.inf}")


Giá trị nan: nan
Giá trị inf: inf


- Thử thực hiện một số so sánh giá trị:
  - nan vs nan?
  - inf vs inf?
  - None vs None?

In [31]:
print(f"nan vs nan = {np.nan == np.nan}")
print(f"inf vs inf = {np.inf == np.inf}")
print(f"None vs None = {None == None}")

nan vs nan = False
inf vs inf = True
None vs None = True


- inf: infinity có nghĩa là 1 số vô cùng lớn
- ví dụ ở đây ta có 1 số bằng 1e1000 (10^1000)
- Bản thân con số này đã rất lớn rồi
- Giờ ta sẽ luỹ thừa nó lên và chắc chắn ta sẽ có 1 kết quả là rất lớn
- Và khi chúng ta thực hiện phép toán đó Python sẽ trả về kết quả là inf (infinity) vì nó quá lớn
- inf (dương vô cùng)

In [32]:
a = 1e1000
a = a**a
a

inf

- tương tự ta sẽ biến nó thành 1 số âm vô vùng

In [33]:
a = 1e1000
a = a**a
-1*a

-inf

- Giờ ta hãy cùng thực hiện 1 phép tính:
  - Hãy tạo ra 2 biến a & b thể hiện cho nó là inf.
  - Hãy thử lấy a-b để xem kết quả của biểu thức dương vô cùng - dương vô cùng sẽ là gì? 
  - Bạn nghĩ là nó sẽ = 0?
  - Đương nhiên là không, kết quả chúng ta nhận được lúc này sẽ là nan (nan là 1 số thực - float)
  - nhưng chắc chắn nan không phải là 0 rồi.
  - Nói chung bạn sẽ nhận được kết quả là nan nếu bạn nhận được 1 phép tính không thể diễn tả dưới dạng số.

In [34]:
a = 1e1000
a = a**a

b = 1e1000
b = b**b

kq = a-b
kq

nan

- Hãy thực hiện chuyển đổi list4 thành numpy array với kiểu float
- Hãy gán giá trị dòng 0 cột 0 = np.nan
- Hãy gán giá trị dòng 1 cột 1 = np.inf
- Hãy hiển thị kết quả của npa2d sau khi thay thế giá trị là 'nan' và 'inf'

In [35]:
npa2d = np.array(list4,'float')
npa2d[0][0] = np.inf
npa2d[1][1] = np.nan
npa2d

array([[ inf,   2.],
       [  3.,  nan],
       [  5.,   6.]])

- Bạn cũng có thể kiểm tra giá trị trong NumPy Array có phải là nan hay inf:
    - Để kiểm tra là nan hay inf thì data type phải là float.
    - Nếu không thì sẽ bị lỗi.
    - Bạn nên nhớ inf, nan có kiểu dữ liệu là float chứ không phải int hay str.

In [36]:
np.isnan(npa2d)


array([[False, False],
       [False,  True],
       [False, False]], dtype=bool)

In [37]:
np.isinf(npa2d)

array([[ True, False],
       [False, False],
       [False, False]], dtype=bool)

- Giờ chúng ta sẽ gộp 2 mảng vào thành 1 như sau:

In [38]:
a = np.isnan(npa2d)|np.isinf(npa2d)
# | this is the or operator in python
a
True|False

True

- Hãy lấy ra các vị trí là True của nan và inf trong npa2d

In [39]:
npa2d[a]
# go into the array and get all the true


array([ inf,  nan])

- Hãy thay thế các giá trị inf và nan thành = 0

In [40]:
npa2d[a] = 0
#make all the True value into 0
npa2d

array([[ 0.,  2.],
       [ 3.,  0.],
       [ 5.,  6.]])

# Chỉ mục và phương pháp cắt lát trong Numpy Array

- Lập chỉ mục được sử dụng để lấy các phần tử riêng lẻ từ một mảng, nhưng nó cũng có thể được sử dụng để lấy toàn bộ hàng, cột hoặc mặt phẳng từ mảng nhiều chiều.

## Chỉ mục trong mảng 1 chiều

- Chúng ta có thể tạo mảng numpy 1 chiều từ danh sách như sau:
- [1, 2, 3, 4]

In [41]:
list = [1, 2, 3, 4]
a = np.array(list)
print(f"a[0] = {a[0]}")
print(f"a[2] = {a[2]}")

a[0] = 1
a[2] = 3


## Chỉ mục trong mảng 2 chiều

- Chúng ta có thể tạo mảng numpy 2 chiều từ danh sách như sau:
- [[1, 2, 3],
   [4, 5, 6],
   [7, 8, 9]]
![image.png](attachment:image.png)

- Lấy ra giá trị ở Hàng 2 & Cột 1 (sẽ lấy được giá trị là 8)

In [42]:
lis = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
npa = np.array(lis)
print(npa[2,1]) #8

8


## Chọn 1 Hàng hoặc 1 Cột nào đó

![image.png](attachment:image.png)

In [43]:
print(npa)
print(f"npa[2]: {npa[2]}")
print(f"npa[:,1]: {npa[:,1]}")
print(f"npa[:,1:3]: {npa[:,1:3]}")
print(f"npa[0:3,1]: {npa[0:3,1]}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
npa[2]: [7 8 9]
npa[:,1]: [2 5 8]
npa[:,1:3]: [[2 3]
 [5 6]
 [8 9]]
npa[0:3,1]: [2 5 8]


## Chỉ mục trong mảng 3 chiều

- Hãy khai báo 1 mảng 3 chiều với các giá trị sau:
- [[[10, 11, 12], [13, 14, 15], [16, 17, 18]],[[20, 21, 22], [23, 24, 25], [26, 27, 28]],[[30, 31, 32], [33, 34, 35], [36, 37, 38]]]
![image-3.png](attachment:image-3.png)
- Mảng 3D giống như một chồng ma trận:
    - Chỉ mục đầu tiên, i, chọn ma trận
    - Chỉ mục thứ hai, j, chọn hàng
    - Chỉ mục thứ ba, k, chọn cột

- Hãy chọn chỉ số ma trận 2 (ma trận cuối cùng), hàng 0, cột 1, cho giá trị 31
- Cú pháp khi sử dụng: npa[chỉ số ma trận, chỉ số hàng, chỉ số cột]

In [44]:
lis = [[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]]
npa = np.array(lis)
print(npa[2,0,1])

31


## Chọn hàng , cột từ mảng 3 chiều

- Trường hợp 1 - xác định hai chỉ số đầu tiên. 
- Trong trường hợp này, bạn đang chọn giá trị i (ma trận) và giá trị j (hàng). 
- Thao tác này sẽ chọn một hàng cụ thể. 
- Trong ví dụ này, chúng tôi đang chọn hàng 2 từ ma trận 1:
![image.png](attachment:image.png)

In [45]:
npa[1,2]


array([26, 27, 28])

- Trường hợp 2 - xác định giá trị i (ma trận) và giá trị k (cột), sử dụng một lát đầy đủ (:) cho giá trị j (hàng). 
- Thao tác này sẽ chọn một cột cụ thể. 
- Trong ví dụ này, chúng tôi đang chọn cột 1 từ ma trận 0:
![image.png](attachment:image.png)

In [46]:
npa[0,:,1]


array([11, 14, 17])

- Trường hợp 3 - xác định giá trị j (hàng) và giá trị k (cột), sử dụng một lát đầy đủ (:) cho giá trị i (ma trận). 
- Thao tác này sẽ tạo một hàng bằng cách lấy cùng một phần tử từ mỗi ma trận. 
- Trong trường hợp này, chúng tôi đang lấy hàng 1, cột 2 từ mỗi ma trận:
![image.png](attachment:image.png)

In [47]:
npa[:,1,2]


array([15, 25, 35])

## Chọn một ma trận trong một mảng 3 chiều

- Trường hợp 01: Nếu chúng ta chỉ xác định chỉ số i, numpy sẽ trả về ma trận tương ứng. 
- Trong ví dụ này, chúng ta sẽ yêu cầu ma trận 2:
![image.png](attachment:image.png)

In [48]:
npa[2]


array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

- Trường hợp 2: nếu chúng ta chỉ xác định giá trị j (sử dụng một lát cắt đầy đủ cho các giá trị i), 
- chúng ta sẽ thu được một ma trận được tạo từ hàng đã chọn được lấy từ mỗi mặt phẳng. 
- Trong ví dụ này, chúng ta sẽ lấy hàng 1:
![image.png](attachment:image.png)

In [49]:
npa[:,1]


array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

- Trường hợp 3 nếu chúng ta chỉ xác định giá trị k (sử dụng các lát cắt đầy đủ cho các giá trị i và j), 
- chúng ta sẽ thu được một ma trận được tạo từ cột đã chọn lấy từ mỗi mặt phẳng. 
- Trong ví dụ này, chúng ta sẽ lấy cột 0:
![image.png](attachment:image.png)

In [50]:
npa[:,:,0]


array([[10, 13, 16],
       [20, 23, 26],
       [30, 33, 36]])

## Cắt lát (Slicing) trong mảng

- Ký hiệu lát cắt chỉ định giá trị bắt đầu và giá trị kết thúc [start: end] và sao chép danh sách từ đầu đến nhưng không bao gồm kết thúc.
- [[10, 11, 12, 13, 14],[15, 16, 17, 18, 19],[20, 21, 22, 23, 24],[25, 26, 27, 28, 29]]
![image.png](attachment:image.png)

In [57]:
lis = [[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]]
npa = np.array(list)

npa[1:,2:4]

array([[[26, 27, 28]],

       [[36, 37, 38]]])

## Cắt một mảng 3 chiều

- Hãy khởi tạo mảng 3 chiều: [[[10, 11, 12], [13, 14, 15], [16, 17, 18]],[[20, 21, 22], [23, 24, 25], [26, 27, 28]],[[30, 31, 32], [33, 34, 35], [36, 37, 38]]]
![image.png](attachment:image.png)

In [58]:
lis = [[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]]
npa= np.array(list)
npa[:2,1:,:2]

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])

-- Chúc mừng các bạn đã hoàn thành nội dung phần 01 rồi!