# Kiến thức Python NumPy Operations

## Xem hình dạng mảng với Shape

- Khai báo numpy và gán biến np để sử dụng.
- Khai báo khởi tạo 1 danh sách: [[8,9,10],[11,12,13]]
- Sử dụng hàm array() để khởi tạo mảng numpy (dtype = 'float')

In [33]:
import numpy as np
lis = [[8,9,10],[11,12,13]] 
npa = np.array(lis,'float')
npa

array([[  8.,   9.,  10.],
       [ 11.,  12.,  13.]])

- Sử dụng shape để kiểm tra kích thước của mảng.
- Theo kết quả bên dưới cho thầy npa2d là 1 mảng 2 chiều có kích thước là 2 dòng và 3 cột.

In [34]:
npa.shape


(2, 3)

## Xoay cấu trúc hình dạng với Reshape

![image.png](attachment:image.png)

- Hãy sử dụng hàm reshape(row,column) để xoay hình dạng với hàng=3 & cột=2.

In [35]:
npa.reshape(3,2)


array([[  8.,   9.],
       [ 10.,  11.],
       [ 12.,  13.]])

* Lưu ý: Khi thiết lập xoay thì tích hàng x cột cần phải không đổi.

## Tạo tham chiếu tới mảng gốc với Ravel

- Sử dụng hàm ravel() để tạo tham chiếu đến mảng gốc.

In [36]:
a = npa.ravel()
a[0] = 100
npa

array([[ 100.,    9.,   10.],
       [  11.,   12.,   13.]])

- Hãy thử thay đổi 1 giá trị phần tử nào đó trong mảng.
- Sau đó bạn hãy kiểm tra biến mảng gốc có bị thay đổi hay không?
- Nếu có thay đổi về giá trị thì có nghĩa là mọi thay đổi lên mảng tham chiếu thì mảng gốc cũng thay đổi theo

In [37]:
list2d=[[ 5 , 9 ,10],
 [11, 12, 13]]
npa2d=np.array(list2d)

npa2d= np.reshape(npa2d, 6)
npa2d

array([ 5,  9, 10, 11, 12, 13])

## Tạo mảng copy với Flatten

- Hãy sử dụng hàm flatten() để tạo 1 bản sao chép mảng.
- Hãy thử thay đổi 1 giá trị phần tử nào đó trong mảng.
- Sau đó bạn hãy kiểm tra biến mảng gốc có bị thay đổi hay không?
- Hàm flatten() sẽ tạo ra 1 bản sao chép mảng nên sẽ ko có tác động nào lên mảng gốc.

In [38]:
val = npa.flatten()
val[0] = 200
print(npa)
print(val)

[[ 100.    9.   10.]
 [  11.   12.   13.]]
[ 200.    9.   10.   11.   12.   13.]


## Tỉnh tổng tích lũy Hàng|Cột với Cumsum

- Hãy sử dụng hàm cumsum() để áp dụng tính tổng tích lũy hàng cột trong mảng.
- Trả về tổng tích lũy của các phần tử dọc theo một trục đã cho.

In [39]:
npa

array([[ 100.,    9.,   10.],
       [  11.,   12.,   13.]])

- Sử dụng thêm axis=0|1 để áp dụng tính tổng tích lũy theo hàng hoặc cột.

In [40]:
# axis=0: tổng tích lũy cho mỗi hang
np.cumsum(npa,axis=0)


array([[ 100.,    9.,   10.],
       [ 111.,   21.,   23.]])

In [41]:
# axis=1: tổng tích lũy cho mỗi cot
np.cumsum(npa,axis=1)


array([[ 100.,  109.,  119.],
       [  11.,   23.,   36.]])

## Thực hiện cắt lát với Slicing

- Như bạn có thể thấy chức năng ‘reshape’ đã cho thấy sự kỳ diệu của nó. 
- Bây giờ, chúng ta hãy thực hiện một thao tác khác, tức là "Cắt lát". 
- Về cơ bản, Slicing là trích xuất tập hợp các phần tử cụ thể từ một mảng. 
- Hãy xem xét ví dụ sau:

![image.png](attachment:image.png)

In [42]:
data = [[8,9],[10,11],[12,13]] 
npa = np.array(data,'float')
npa

array([[  8.,   9.],
       [ 10.,  11.],
       [ 12.,  13.]])

In [43]:
npa[1]

array([ 10.,  11.])

In [45]:
npa[:,1]

array([  9.,  11.,  13.])

In [46]:
npa[:2,1]

array([  9.,  11.])

In [47]:
npa

array([[  8.,   9.],
       [ 10.,  11.],
       [ 12.,  13.]])

In [54]:
npa[:2,1].astype(np.int32)

array([ 9, 11], dtype=int32)

Hoàn thành nhiệm vụ!